;Music defines
def MUS_CNT				equ $12

def MUS_CUTMAN			equ $00
def MUS_ICEMAN			equ $01
def MUS_ELECMAN			equ $02
def MUS_FIREMAN			equ $03
def MUS_BOSS			equ $04
def MUS_VICTORY			equ $05
def MUS_WILY1			equ $06
def MUS_WILY_UNKNOWN	equ $07
def MUS_STAGE_START		equ $08
def MUS_WILY2			equ $09
def MUS_STAGE_SELECT	equ $0A
def MUS_WILY_INTRO		equ $0B
def MUS_END_GAME		equ $0C
def MUS_GET_WEAPON		equ $0D
def MUS_TITLE			equ $0E
def MUS_UNKNOWN			equ $0F
def MUS_PASSWORD		equ $10
def MUS_END_GAME_ALT	equ $11

;SFX defines
def SFX_CNT				equ $1C

def SFX_UFO				equ $00
def SFX_EXPLODE			equ $01
def SFX_ELECTRICITY		equ $02
def SFX_SHOOT			equ $03
def SFX_ENEMY_SHOOT		equ $04
def SFX_PLAYER_HIT		equ $05
def SFX_BEEP1			equ $06
def SFX_LAND			equ $07
def SFX_ENEMY_HIT		equ $08
def SFX_BEEP2			equ $09
def SFX_SELECT			equ $0A
def SFX_BEEP3			equ $0B
def SFX_BEEP4			equ $0C
def SFX_CUT_ATTACK		equ $0D
def SFX_PLAYER_EXPLODE	equ $0E
def SFX_EXTRA_LIFE		equ $0F
def SFX_WHEEL			equ $10
def SFX_HEALTH			equ $11
def SFX_ICE_ATTACK		equ $12
def SFX_FIRE_ATTACK		equ $13
def SFX_ELEC_ATTACK		equ $14
def SFX_BLOCK			equ $15
def SFX_BIG_EYE			equ $16
def SFX_TELEPORT		equ $17
def SFX_SHING			equ $18
def SFX_HEAT1			equ $19
def SFX_HEAT2			equ $1A
def SFX_HEAT3			equ $1B